# storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mycalss
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

---
#volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: jenkins-pv-claim
   namespace: devops-tools
spec:
   storageClassName: mycalss
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
