- name: install packages
  hosts: bastionvm
  tasks:

  - name: update
    apt: 
      update_cache: yes   
    ignore_errors: yes

  - name: Install  packages 1
    apt:
      name: apt-transport-https
      state: present

  - name: Install  packages 2
    apt:
      name: ca-certificates 
      state: present

  - name: Install  packages 3
    apt:
      name: gnupg
      state: present

  - name: add key
    shell: |
      echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      
  - name: update
    apt: 
      update_cache: yes   
    ignore_errors: yes     

  - name: install gcloud-sdk and initialize gcloud
    apt:
      name: google-cloud-sdk-gke-gcloud-auth-plugin
      state: present


  - name: install kubectl
    apt:
      name: kubectl
      state: present


  - name: get-credentials
    shell: gcloud container clusters get-credentials my-cluster1 --zone europe-west1-b --project iti-gproject
#---------------------------------------------------------------------------------------

#install docker 

  - name: Install  packages 4
    apt:
      name: lsb-release
      state: present

  - name: Creates directory
    file:
      path: /etc/apt/keyrings
      state: directory

  - name: Check if gpg exists
    stat:
      path: /etc/apt/keyrings/docker.gpg
    register: result

  - name: add gpg key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    when: not result.stat.exists

  - name: add repo
    shell: |
      echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: update
    apt: 
      update_cache: yes   
    ignore_errors: yes 

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io

  - name: add user to docker group
    shell: |
      usermod -aG docker bassem
      chmod 666 /var/run/docker.sock